spring.application.name=backend

# Temporarily disable DB auto-setup so the app can start
# Not ready to connect MySQL yet
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration